spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test?charset=UTF8"
    username: root
    password: 1234

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  issuer: todo-spring
  secret-key: secretsecret
  expiry-seconds: 3600

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG

