spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test?charset=UTF8"
    username: root
    password: 1234

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: d68555242b1fd89f57eb
            clientSecret: 4ead9a6bd7e6a47ff430cc0edd930188419aee48


jwt:
  issuer: todo-spring
  secret-key: secretsecret
  expiry-seconds: 3600
